/* Generated by scripts/gen-content.mjs from site-content.json. Do not edit. */
import type { Person, Category, ProcessStep } from './schema';

export type PaletteProject = {
  slug: string;
  name: string;
  category: string;
  tagline: string;
  stack: string[];
  repo_url: string;
};

export const person: Person = {
  "name": "Pratyush Vatsa",
  "title": "Robotics, Automation & Product Engineering Studio",
  "tagline": "ROS 2, PX4, industrial automation and applied AI. We write software only, and it runs on real machines — not just in simulation.",
  "location": "India — working with clients worldwide",
  "email": "pratyushvatsa2018@gmail.com",
  "github": "https://github.com/Pratyush150",
  "fiverr": "https://www.fiverr.com/s/YLvqY7z",
  "linkedin": "https://www.linkedin.com/in/pratyush-vatsa-a03292372"
};

export const contact: { headline: string; blurb: string; note: string } =
  {
  "headline": "Tell us what is failing",
  "blurb": "Describe the machine or the process, the versions, and send the evidence. We reply within one working day with an honest answer about whether we can help and what it would cost. If it is not something we can do well, we will say so.",
  "note": "Best first message: what the system is, what it does wrong, when it started, and a link to a log, a bag file, a register map or a document sample. That gets you a useful answer instead of a scheduling email."
};

export const processSteps: ProcessStep[] = [
  {
    "step": 1,
    "title": "Tell us what is going wrong",
    "detail": "Describe the machine or the process, the versions, and send whatever evidence you have — a log, a bag file, a register map, a screenshot of the failure, a document corpus. We will tell you within a working day whether this is something we can fix and roughly what it takes."
  },
  {
    "step": 2,
    "title": "Paid diagnosis or scoping first",
    "detail": "We analyse the evidence and send a written report: what is actually failing, the reasoning behind that conclusion, what we ruled out, and the specific changes we would make. It is a fixed low price and it stands on its own. If you take the report and do the work in-house, that is a fine outcome."
  },
  {
    "step": 3,
    "title": "Implementation with visible progress",
    "detail": "If you want it built, we scope it against the report and work in visible increments. You get running code, not a status update. Scope changes get flagged when we find them, not at delivery."
  },
  {
    "step": 4,
    "title": "Handover you can maintain",
    "detail": "Code with comments and tests, a README that explains how to run it, and a recorded walkthrough of the architecture and the parameters worth touching. On Premium engagements we stay available while you run it on your own hardware or put it in front of real users."
  }
];

export const categories: Category[] = [
  {
    "slug": "robotics-control",
    "name": "Robotics & control",
    "blurb": "ROS 2, PX4 and ArduPilot drone autonomy, MAVLink integration, LiDAR SLAM, control systems and state estimation, real-time perception on Jetson and Raspberry Pi. Our code runs on real vehicles, not just in simulation, so it has already met the failure modes you are hitting."
  },
  {
    "slug": "simulation-testing",
    "name": "Simulation & testing",
    "blurb": "Gazebo, Isaac Sim and AirSim environments for testing robots before they exist in metal, plus automated regression testing of robot behaviour."
  },
  {
    "slug": "automation-ai",
    "name": "Automation & AI",
    "blurb": "Industrial automation, workflow automation, AI chatbots and FAQ assistants, LLM integrations, internal tools that remove manual work."
  },
  {
    "slug": "product",
    "name": "Product",
    "blurb": "Mobile apps and web applications, built by people who also write embedded real-time code, so performance and reliability are not afterthoughts."
  }
];

export const projects: PaletteProject[] = [
  {
    "slug": "px4-mavlink-companion",
    "name": "px4-mavlink-companion",
    "category": "Robotics & control",
    "tagline": "MAVLink plumbing between a flight controller and a companion computer, with the failure modes handled.",
    "stack": [
      "Python",
      "MAVLink",
      "pymavlink",
      "PX4",
      "ArduPilot",
      "pyserial",
      "UDP"
    ],
    "repo_url": "https://github.com/Pratyush150/px4-mavlink-companion"
  },
  {
    "slug": "drone-control-toolkit",
    "name": "drone-control-toolkit",
    "category": "Robotics & control",
    "tagline": "PID, cascade, LQR, attitude estimation and motor mixing, with the parts that decide whether they fly.",
    "stack": [
      "Python",
      "NumPy",
      "control theory",
      "Kalman filtering",
      "pytest"
    ],
    "repo_url": "https://github.com/Pratyush150/drone-control-toolkit"
  },
  {
    "slug": "jetson-realtime-detection",
    "name": "jetson-realtime-detection",
    "category": "Robotics & control",
    "tagline": "Real-time detection and tracking on boards with a thermal budget, not a workstation GPU.",
    "stack": [
      "Python",
      "NumPy",
      "YOLO",
      "TensorRT",
      "ONNX Runtime",
      "Hailo",
      "OpenCV",
      "ROS 2"
    ],
    "repo_url": "https://github.com/Pratyush150/jetson-realtime-detection"
  },
  {
    "slug": "flight-log-analyzer",
    "name": "flight-log-analyzer",
    "category": "Robotics & control",
    "tagline": "\"The drone flew badly. Why?\" — answered from the log, with the evidence attached.",
    "stack": [
      "Python",
      "NumPy",
      "pyulog",
      "pymavlink",
      "ULog",
      "dataflash",
      "SVG"
    ],
    "repo_url": "https://github.com/Pratyush150/flight-log-analyzer"
  },
  {
    "slug": "lidar-slam-toolkit",
    "name": "lidar-slam-toolkit",
    "category": "Robotics & control",
    "tagline": "SLAM rarely fails because the algorithm is wrong. This finds the reason it actually failed.",
    "stack": [
      "Python",
      "NumPy",
      "ROS 2",
      "LIO-SAM",
      "Cartographer",
      "RTAB-Map",
      "rosbag2"
    ],
    "repo_url": "https://github.com/Pratyush150/lidar-slam-toolkit"
  },
  {
    "slug": "ros2-diffdrive-robot",
    "name": "ros2-diffdrive-robot",
    "category": "Robotics & control",
    "tagline": "The whole path from a velocity command to a turning wheel and back to a measured speed.",
    "stack": [
      "ROS 2",
      "Gazebo",
      "Xacro",
      "URDF",
      "Python",
      "pyserial",
      "Arduino"
    ],
    "repo_url": "https://github.com/Pratyush150/ros2-diffdrive-robot"
  },
  {
    "slug": "robot-description-urdf-xacro",
    "name": "robot-description-urdf-xacro",
    "category": "Robotics & control",
    "tagline": "The same robot written twice — plain URDF and Xacro — so the difference is visible, not described.",
    "stack": [
      "URDF",
      "Xacro",
      "ROS 2",
      "RViz2",
      "Gazebo"
    ],
    "repo_url": "https://github.com/Pratyush150/robot-description-urdf-xacro"
  },
  {
    "slug": "cpp-for-robotics",
    "name": "cpp-for-robotics",
    "category": "Robotics & control",
    "tagline": "C++ fundamentals taught against the situations the syntax is actually for in robotics code.",
    "stack": [
      "C++",
      "Eigen",
      "g++"
    ],
    "repo_url": "https://github.com/Pratyush150/cpp-for-robotics"
  },
  {
    "slug": "ros2-drone-bringup",
    "name": "ros2-drone-bringup",
    "category": "Simulation & testing",
    "tagline": "ROS 2 Humble bringup for a PX4 or ArduPilot multirotor, with PX4 SITL and Gazebo launch files.",
    "stack": [
      "ROS 2 Humble",
      "MAVROS",
      "PX4 SITL",
      "Gazebo",
      "Python",
      "rclpy",
      "RViz2",
      "YAML"
    ],
    "repo_url": "https://github.com/Pratyush150/ros2-drone-bringup"
  },
  {
    "slug": "robot-sim-test-harness",
    "name": "robot-sim-test-harness",
    "category": "Simulation & testing",
    "tagline": "Scenario-driven regression testing for robot behaviour: assert what the robot must and must not do, and fail the build when a change breaks it.",
    "stack": [
      "Python",
      "PyYAML",
      "Gazebo",
      "AirSim",
      "Isaac Sim",
      "JUnit XML",
      "pytest"
    ],
    "repo_url": "https://github.com/Pratyush150/robot-sim-test-harness"
  },
  {
    "slug": "llm-faq-assistant",
    "name": "llm-faq-assistant",
    "category": "Automation & AI",
    "tagline": "A FAQ assistant for your own documents that says \"I don't know\" when it does not know — and measures how often it is right.",
    "stack": [
      "Python",
      "stdlib only",
      "RAG",
      "BM25",
      "RRF",
      "vector search",
      "LLM APIs (optional)",
      "pytest"
    ],
    "repo_url": "https://github.com/Pratyush150/llm-faq-assistant"
  },
  {
    "slug": "workflow-automation-engine",
    "name": "workflow-automation-engine",
    "category": "Automation & AI",
    "tagline": "A workflow engine for automation you have to operate: retries that know what is worth retrying, and runs you can resume.",
    "stack": [
      "Python",
      "stdlib only",
      "DAG scheduling",
      "cron/zoneinfo",
      "HTTP + SMTP connectors",
      "pytest"
    ],
    "repo_url": "https://github.com/Pratyush150/workflow-automation-engine"
  },
  {
    "slug": "industrial-automation-suite",
    "name": "industrial-automation-suite",
    "category": "Automation & AI",
    "tagline": "Get data off your PLCs and make it visible and actionable — acquisition, alarms, a compressing historian, OEE and a dashboard.",
    "stack": [
      "Python",
      "PyYAML",
      "Modbus TCP/RTU",
      "OPC-UA (asyncua)",
      "MQTT Sparkplug B",
      "SQLite",
      "pytest"
    ],
    "repo_url": "https://github.com/Pratyush150/industrial-automation-suite"
  },
  {
    "slug": "fleet-ops-dashboard",
    "name": "fleet-ops-dashboard",
    "category": "Product",
    "tagline": "A browser ground station for a mixed fleet, with the telemetry simulator that makes it testable.",
    "stack": [
      "TypeScript",
      "React 18",
      "Vite 5",
      "Tailwind CSS 3",
      "Vitest",
      "SVG"
    ],
    "repo_url": "https://github.com/Pratyush150/fleet-ops-dashboard"
  },
  {
    "slug": "ground-station-mobile",
    "name": "ground-station-mobile",
    "category": "Product",
    "tagline": "A phone-sized ground-control station that decodes MAVLink itself and never shows a stale number as if it were live.",
    "stack": [
      "TypeScript",
      "React Native 0.74",
      "Expo SDK 51",
      "MAVLink v1/v2",
      "Vitest",
      "UDP/TCP/serial"
    ],
    "repo_url": "https://github.com/Pratyush150/ground-station-mobile"
  }
];
