/* Generated by scripts/gen-media-manifest.mjs. Do not edit. */
export type ClipAssets = {
  webm?: string;
  mp4?: string;
  poster?: string;
  posterWebp?: string;
  posterAvif?: string;
};

export const MEDIA: Record<string, ClipAssets> = {
  "detection-coco-val2017": {
    "poster": "/media/detection-coco-val2017-poster.jpg",
    "mp4": "/media/detection-coco-val2017.mp4",
    "webm": "/media/detection-coco-val2017.webm"
  },
  "fleet-ops-dashboard": {
    "poster": "/media/fleet-ops-dashboard-poster.jpg",
    "mp4": "/media/fleet-ops-dashboard.mp4"
  },
  "posegraph-sphere2500-converging": {
    "poster": "/media/posegraph-sphere2500-converging-poster.jpg",
    "mp4": "/media/posegraph-sphere2500-converging.mp4"
  },
  "svslam-kitti-tracked-features": {
    "poster": "/media/svslam-kitti-tracked-features-poster.jpg",
    "mp4": "/media/svslam-kitti-tracked-features.mp4"
  },
  "svslam-kitti-trajectory": {
    "poster": "/media/svslam-kitti-trajectory-poster.jpg",
    "mp4": "/media/svslam-kitti-trajectory.mp4",
    "webm": "/media/svslam-kitti-trajectory.webm"
  }
};

export const MEDIA_IDS: string[] = [
  "detection-coco-val2017",
  "fleet-ops-dashboard",
  "posegraph-sphere2500-converging",
  "svslam-kitti-tracked-features",
  "svslam-kitti-trajectory"
];
