/**
 * Trim `site-content.json` down to the fields this page actually renders, and
 * emit it as a module.
 *
 *   node scripts/gen-content.mjs
 *
 * Why: the page is prerendered *and* hydrated, so every string it renders is
 * paid for twice — once in the HTML and once in the JS bundle. The content file
 * is 55 KB of JSON, of which 32 KB is project descriptions and highlights and
 * 10 KB is a services table that this design does not use. Importing it whole
 * puts all of that in the bundle. This generator keeps `site-content.json` as
 * the single editable source of truth and gives the build only what it needs.
 *
 * Edit `src/content/site-content.json`; never edit the generated file.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = fileURLToPath(new URL('../src/content/site-content.json', import.meta.url));
const out = fileURLToPath(new URL('../src/content/content.generated.ts', import.meta.url));

const d = JSON.parse(readFileSync(src, 'utf8'));

const trimmed = {
  person: d.person,
  contact: d.contact,
  process: d.process,
  categories: d.categories.map(({ slug, name }) => ({ slug, name })),
  // The command palette lists every repository by name and one line. It does
  // not need the descriptions or the highlight bullets.
  projects: d.projects.map(({ slug, name, category, tagline, stack, repo_url }) => ({
    slug,
    name,
    category,
    tagline,
    stack,
    repo_url,
  })),
};

const body = `/* Generated by scripts/gen-content.mjs from site-content.json. Do not edit. */
import type { Person, Category, ProcessStep } from './schema';

export type PaletteProject = {
  slug: string;
  name: string;
  category: string;
  tagline: string;
  stack: string[];
  repo_url: string;
};

export const person: Person = ${JSON.stringify(trimmed.person, null, 2)};

export const contact: { headline: string; blurb: string; note: string } =
  ${JSON.stringify(trimmed.contact, null, 2)};

export const processSteps: ProcessStep[] = ${JSON.stringify(trimmed.process, null, 2)};

export const categories: Category[] = ${JSON.stringify(
  d.categories.map(({ slug, name, blurb }) => ({ slug, name, blurb })),
  null,
  2,
)};

export const projects: PaletteProject[] = ${JSON.stringify(trimmed.projects, null, 2)};
`;

writeFileSync(out, body);
console.log(
  `content: ${(readFileSync(src).length / 1024).toFixed(1)} KB JSON -> ` +
    `${(Buffer.byteLength(body) / 1024).toFixed(1)} KB module ` +
    `(${trimmed.projects.length} repositories, ${trimmed.process.length} process steps)`,
);
